#!/usr/bin/env node
// Automated font subsetting at build time.
// Downloads remote font files and emits Latin + Latin-Ext subsets to
// public/fonts/, plus a ready-to-link @font-face CSS file.
//
// Add new fonts by appending to FONTS below.
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import subsetFont from "subset-font";

const OUT_DIR = path.resolve("public/fonts");
const CSS_OUT = path.join(OUT_DIR, "subset.css");

// Glyph coverage: Basic Latin + Latin-1 Supplement + Latin Extended-A
// (covers PT-BR diacritics: ã, ç, õ, é, etc.) + common punctuation.
const TEXT = (() => {
  const ranges = [
    [0x20, 0x7e],   // Basic Latin
    [0xa0, 0xff],   // Latin-1 Supplement
    [0x100, 0x17f], // Latin Extended-A
    [0x2018, 0x201f], // smart quotes
    [0x2013, 0x2014], // en/em dash
  ];
  let s = "";
  for (const [a, b] of ranges) for (let c = a; c <= b; c++) s += String.fromCodePoint(c);
  return s;
})();

const FONTS = [
  {
    family: "Dancing Script",
    weight: 700,
    style: "normal",
    // Direct Google Fonts woff2 URL for Dancing Script 700.
    src: "https://fonts.gstatic.com/s/dancingscript/v25/If2cXTr6YS-zF4S-kcSWSVi_swLkjm4ITPRHQUuxYg.woff2",
    file: "dancing-script-700.woff2",
  },
];

async function fetchBuf(url) {
  const res = await fetch(url, {
    headers: {
      // Modern UA so Google serves woff2.
      "user-agent":
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36",
    },
  });
  if (!res.ok) throw new Error(`fetch ${url} -> ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

await mkdir(OUT_DIR, { recursive: true });

const cssParts = ["/* Generated by scripts/subset-fonts.mjs — do not edit by hand. */"];

for (const f of FONTS) {
  const cached = path.join(OUT_DIR, `_src-${f.file}`);
  let buf;
  if (existsSync(cached)) {
    buf = await readFile(cached);
  } else {
    console.log(`↓ ${f.family} ${f.weight}`);
    buf = await fetchBuf(f.src);
    await writeFile(cached, buf);
  }

  const subset = await subsetFont(buf, TEXT, { targetFormat: "woff2" });
  const outPath = path.join(OUT_DIR, f.file);
  await writeFile(outPath, subset);
  const kb = (subset.length / 1024).toFixed(1);
  console.log(`✓ ${f.file} (${kb} KB)`);

  cssParts.push(
    `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: U+0020-007E, U+00A0-017F, U+2013-2014, U+2018-201F;
}`
  );
}

await writeFile(CSS_OUT, cssParts.join("\n\n") + "\n");
console.log(`✓ wrote ${path.relative(process.cwd(), CSS_OUT)}`);