/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as LotesIndexRouteImport } from './routes/lotes.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as CompraDiretaIndexRouteImport } from './routes/compra-direta.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as LotesLotIdRouteImport } from './routes/lotes.$lotId'
import { Route as EventosEventSlugRouteImport } from './routes/eventos.$eventSlug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesIndexRoute = LotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LotesRoute,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const CompraDiretaIndexRoute = CompraDiretaIndexRouteImport.update({
  id: '/compra-direta/',
  path: '/compra-direta/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesLotIdRoute = LotesLotIdRouteImport.update({
  id: '/$lotId',
  path: '/$lotId',
  getParentRoute: () => LotesRoute,
} as any)
const EventosEventSlugRoute = EventosEventSlugRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => EventosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ao-vivo': typeof AoVivoRoute
  '/cadastro': typeof CadastroRoute
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRouteWithChildren
  '/painel': typeof PainelRoute
  '/sobre': typeof SobreRoute
  '/eventos/$eventSlug': typeof EventosEventSlugRoute
  '/lotes/$lotId': typeof LotesLotIdRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/compra-direta/': typeof CompraDiretaIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/lotes/': typeof LotesIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ao-vivo': typeof AoVivoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/sobre': typeof SobreRoute
  '/eventos/$eventSlug': typeof EventosEventSlugRoute
  '/lotes/$lotId': typeof LotesLotIdRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/compra-direta': typeof CompraDiretaIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/lotes': typeof LotesIndexRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ao-vivo': typeof AoVivoRoute
  '/cadastro': typeof CadastroRoute
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRouteWithChildren
  '/painel': typeof PainelRoute
  '/sobre': typeof SobreRoute
  '/eventos/$eventSlug': typeof EventosEventSlugRoute
  '/lotes/$lotId': typeof LotesLotIdRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/compra-direta/': typeof CompraDiretaIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/lotes/': typeof LotesIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ao-vivo'
    | '/cadastro'
    | '/eventos'
    | '/login'
    | '/lotes'
    | '/painel'
    | '/sobre'
    | '/eventos/$eventSlug'
    | '/lotes/$lotId'
    | '/noticias/$slug'
    | '/compra-direta/'
    | '/eventos/'
    | '/lotes/'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ao-vivo'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/sobre'
    | '/eventos/$eventSlug'
    | '/lotes/$lotId'
    | '/noticias/$slug'
    | '/compra-direta'
    | '/eventos'
    | '/lotes'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ao-vivo'
    | '/cadastro'
    | '/eventos'
    | '/login'
    | '/lotes'
    | '/painel'
    | '/sobre'
    | '/eventos/$eventSlug'
    | '/lotes/$lotId'
    | '/noticias/$slug'
    | '/compra-direta/'
    | '/eventos/'
    | '/lotes/'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AoVivoRoute: typeof AoVivoRoute
  CadastroRoute: typeof CadastroRoute
  EventosRoute: typeof EventosRouteWithChildren
  LoginRoute: typeof LoginRoute
  LotesRoute: typeof LotesRouteWithChildren
  PainelRoute: typeof PainelRoute
  SobreRoute: typeof SobreRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  CompraDiretaIndexRoute: typeof CompraDiretaIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes/': {
      id: '/lotes/'
      path: '/'
      fullPath: '/lotes/'
      preLoaderRoute: typeof LotesIndexRouteImport
      parentRoute: typeof LotesRoute
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/compra-direta/': {
      id: '/compra-direta/'
      path: '/compra-direta'
      fullPath: '/compra-direta/'
      preLoaderRoute: typeof CompraDiretaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes/$lotId': {
      id: '/lotes/$lotId'
      path: '/$lotId'
      fullPath: '/lotes/$lotId'
      preLoaderRoute: typeof LotesLotIdRouteImport
      parentRoute: typeof LotesRoute
    }
    '/eventos/$eventSlug': {
      id: '/eventos/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/eventos/$eventSlug'
      preLoaderRoute: typeof EventosEventSlugRouteImport
      parentRoute: typeof EventosRoute
    }
  }
}

interface EventosRouteChildren {
  EventosEventSlugRoute: typeof EventosEventSlugRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosEventSlugRoute: EventosEventSlugRoute,
  EventosIndexRoute: EventosIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface LotesRouteChildren {
  LotesLotIdRoute: typeof LotesLotIdRoute
  LotesIndexRoute: typeof LotesIndexRoute
}

const LotesRouteChildren: LotesRouteChildren = {
  LotesLotIdRoute: LotesLotIdRoute,
  LotesIndexRoute: LotesIndexRoute,
}

const LotesRouteWithChildren = LotesRoute._addFileChildren(LotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AoVivoRoute: AoVivoRoute,
  CadastroRoute: CadastroRoute,
  EventosRoute: EventosRouteWithChildren,
  LoginRoute: LoginRoute,
  LotesRoute: LotesRouteWithChildren,
  PainelRoute: PainelRoute,
  SobreRoute: SobreRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  CompraDiretaIndexRoute: CompraDiretaIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
