CREATE TABLE public.audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,action text NOT NULL,entity_type text NOT NULL,entity_id uuid,old_data jsonb,new_data jsonb,ip_address text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.audit_logs TO authenticated;GRANT ALL ON public.audit_logs TO service_role;ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;CREATE POLICY audit_logs_admin_read ON public.audit_logs FOR SELECT TO authenticated USING(public.is_admin());CREATE POLICY audit_logs_admin_create ON public.audit_logs FOR INSERT TO authenticated WITH CHECK(public.is_admin());
CREATE TABLE public.db_errors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),function_name text,error_message text,error_context text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.db_errors TO authenticated;GRANT ALL ON public.db_errors TO service_role;ALTER TABLE public.db_errors ENABLE ROW LEVEL SECURITY;CREATE POLICY db_errors_admin ON public.db_errors FOR SELECT TO authenticated USING(public.is_admin());
CREATE TABLE public.webhook_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),gateway_name text NOT NULL,external_id text NOT NULL,event_type text,payload jsonb,status text DEFAULT 'processed',error_message text,processed_at timestamptz DEFAULT now(),retry_count integer DEFAULT 0,next_retry_at timestamptz,scheduled_for timestamptz DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(gateway_name,external_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.webhook_events TO authenticated;GRANT ALL ON public.webhook_events TO service_role;ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;CREATE POLICY webhook_events_admin ON public.webhook_events FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
CREATE TABLE public.notification_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),type text,title text,message text,recipient_email text,status text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.notification_logs TO authenticated;GRANT ALL ON public.notification_logs TO service_role;ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;CREATE POLICY notification_logs_admin ON public.notification_logs FOR SELECT TO authenticated USING(public.is_admin());CREATE POLICY notification_logs_admin_create ON public.notification_logs FOR INSERT TO authenticated WITH CHECK(public.is_admin());
CREATE TABLE public.seo_audits(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),status text NOT NULL DEFAULT 'pending',total_items integer DEFAULT 0,error_count integer DEFAULT 0,warning_count integer DEFAULT 0,healthy_count integer DEFAULT 0,processed_items integer DEFAULT 0,progress_message text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.seo_audits TO authenticated;GRANT ALL ON public.seo_audits TO service_role;ALTER TABLE public.seo_audits ENABLE ROW LEVEL SECURITY;CREATE POLICY seo_audits_admin ON public.seo_audits FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
CREATE TABLE public.seo_audit_details(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),audit_id uuid REFERENCES public.seo_audits(id) ON DELETE CASCADE,item_id uuid NOT NULL,item_type text NOT NULL,item_name text,issues jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.seo_audit_details TO authenticated;GRANT ALL ON public.seo_audit_details TO service_role;ALTER TABLE public.seo_audit_details ENABLE ROW LEVEL SECURITY;CREATE POLICY seo_details_admin ON public.seo_audit_details FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
CREATE TABLE public.email_smtp_settings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),host text NOT NULL DEFAULT '',port integer NOT NULL DEFAULT 465,secure boolean NOT NULL DEFAULT true,username text NOT NULL DEFAULT '',password text NOT NULL DEFAULT '',from_email text NOT NULL DEFAULT '',from_name text NOT NULL DEFAULT 'NC Agro Leilões',reply_to text,enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.email_smtp_settings TO authenticated;GRANT ALL ON public.email_smtp_settings TO service_role;ALTER TABLE public.email_smtp_settings ENABLE ROW LEVEL SECURITY;CREATE POLICY email_smtp_admin ON public.email_smtp_settings FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
CREATE TABLE public.email_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL UNIQUE,label text NOT NULL,category text NOT NULL DEFAULT 'transactional',subject text NOT NULL DEFAULT '',header_html text NOT NULL DEFAULT '',body_html text NOT NULL DEFAULT '',footer_html text NOT NULL DEFAULT '',variables jsonb NOT NULL DEFAULT '[]',enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.email_templates TO authenticated;GRANT ALL ON public.email_templates TO service_role;ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;CREATE POLICY email_templates_admin ON public.email_templates FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
CREATE TABLE public.email_send_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),template_name text,to_email text NOT NULL,subject text,status text NOT NULL,error_message text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.email_send_logs TO authenticated;GRANT ALL ON public.email_send_logs TO service_role;ALTER TABLE public.email_send_logs ENABLE ROW LEVEL SECURITY;CREATE POLICY email_logs_admin_read ON public.email_send_logs FOR SELECT TO authenticated USING(public.is_admin());CREATE POLICY email_logs_admin_create ON public.email_send_logs FOR INSERT TO authenticated WITH CHECK(public.is_admin());
CREATE INDEX idx_audit_created ON public.audit_logs(created_at DESC);CREATE INDEX idx_webhook_retry ON public.webhook_events(status,retry_count,next_retry_at);CREATE INDEX idx_notification_rate ON public.notification_logs(recipient_email,type,created_at DESC);CREATE INDEX idx_email_logs_created ON public.email_send_logs(created_at DESC);
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['email_smtp_settings','email_templates'] LOOP EXECUTE format('CREATE TRIGGER touch_%I_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()',t,t);END LOOP;END$$;
INSERT INTO public.email_templates(name,label,category,subject,body_html,variables) VALUES
('welcome','Boas-vindas','transactional','Bem-vindo à NC Agro Leilões','<p>Olá, {{nome}}. Seu cadastro foi recebido.</p>','["nome"]'),
('user_approved','Cadastro aprovado','transactional','Seu cadastro foi aprovado','<p>Olá, {{nome}}. Você já pode participar dos leilões.</p>','["nome"]'),
('outbid','Lance superado','transactional','Seu lance foi superado','<p>O lote {{lote}} recebeu um novo lance.</p>','["lote"]');